Further fix tests using proxyquire on Node.js 22+ [skip build]
TypeError: Cannot read properties of undefined (reading 'require')
    at Proxyquire.load (/home/runner/work/emcee-tournament-bot/emcee-tournament-bot/node_modules/proxyquire/lib/proxyquire.js:129:72)

thlorenz/proxyquire#277
\#718