Fix tests on Node.js 22+ [skip build]
import sinon, { SinonSandbox } from "sinon";
                ^^^^^^^^^^^^
SyntaxError: The requested module 'sinon' does not provide an export named 'SinonSandbox'

\#718